config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  # Theme switching route !!not a page!!
  get 'theme', to: 'home#index'

  resources :supports, only: [:new, :create]
  resources :contacts, only: [:create, :index, :destroy]
  resources :landings, only: [:show]
  resources :banners do
    resources :banner_images
  end
  resources :donations, except: [:edit, :index, :show]
  resources :scores, except: [:edit]
  resources :games, except: [:edit] do
    resources :images
  end

  resources :home_tabs, only: [:create, :destroy, :update] do
    resources :ludo_images
  end

  resources :articles do
    resources :images
    resources :comments, only: [:create, :edit, :new]
    resources :likes, only: [:create, :edit, :new, :destroy]
  end
  devise_for :users, except: [:index]

  # Admin dashboard

  resources :admins, only: [:index]
  namespace :admin do
    resources :home_tabs, only: [:index]
    resources :supports, except: [:new, :create, :update, :edit]
    resources :banners
    resources :donations, only: [:edit, :index, :show]
    resources :scores, only: [:edit, :index]
    resources :games
    resources :articles do
      resources :comments
    end
    resources :users, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # TicTacToe
  namespace :tictactoe do
    resources :tictactoe_grids, only: [:update]
    resources :tictactoe_users, only: [:create, :destroy]
    resources :tictactoes, only: [:show, :create, :update] do
      get 'get_status'
      get 'get_grid'
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :likes
  has_one_attached :image
  after_create :send_news

  private

  def send_news
    users = User.all
    users.each do |user|
      UserMailer.news_actuality(self, user).deliver_now
    end
  end
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_one_attached :banner_image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user 
end
 

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :me, :class_name => "User"
  belongs_to :friend, :class_name => "User"
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :game
  belongs_to :user
  after_create :send_donation

  private

  def send_donation
    UserMailer.confirm_donation(self).deliver_now
  end
end
 

app/models/game.rb
class Game < ApplicationRecord
  has_many :donations
  has_many :scores
  has_many :users, through: :scores
  has_one_attached :image
end

app/models/home_tab.rb
class HomeTab < ApplicationRecord
	has_one_attached :ludo_image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user 
end
  

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :game
  belongs_to :user 
end
 

app/models/status.rb
class Status < ApplicationRecord
  has_many :users 
end

app/models/support.rb
class Support < ApplicationRecord
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "adresse email non valide" }
  validates :title, presence: true
  validates :description, presence: true
end

app/models/tictactoe.rb
class Tictactoe < ApplicationRecord
	has_many :tictactoe_user
	has_one :tictactoe_grid
	validates :status, presence: true

	
end

app/models/tictactoe_grid.rb
class TictactoeGrid < ApplicationRecord
	belongs_to :tictactoe
end

app/models/tictactoe_user.rb
class TictactoeUser < ApplicationRecord
	belongs_to :tictactoe
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  belongs_to :status, optional: true
  has_many :comments
  has_many :likes
  has_many :scores
  has_many :donations
  has_many :games, through: :scores
  has_one_attached :avatar
  has_many :contact, foreign_key: "friend_id", class_name: "Contact"
  after_create :set_status
  after_create :welcome_send

  private

  def set_status
    self.update(status_id: 1)
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminsController
  layout "ajax_gets"
  before_action :set_article, except: [:index]
  respond_to :js, :html, :json


  def index
    @articles = Article.all.order('created_at DESC')
  end

  def show

  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :article_images)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, except: [:index, :create]
  respond_to :js, :html, :json


  def index
    @articles = Article.all.sort.reverse
    @comments = Comment.all.sort.reverse
    @like = Like.all
  end

  def update
    flash[:notice] = "Article mis à jour" if @article.update_attributes(article_params)
    respond_with(@article)
  end

  def show

  end

  def create
    @article = Article.new(article_params)
    flash[:notice] = "Article créé !" if @article.save
    respond_with(@article)
  end

  def destroy
    flash[:notice] = "Article supprimé" if @article.destroy
    respond_with(@article)
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.permit(:title, :description, :image, :id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/articles/_comment.html.erb
<div class="d-block p-3 background-comment border-comment m-4 rounded">
  <h3 class=""><%= comment.user.username %></h3>
  <p><%= comment.description %></p>
  <p><%= tidy_date(comment.created_at) %></p>
</div>

app/views/articles/_comments_modal.html.erb
<div class="modal fade game-modal" id="articleComments<%= article.id %>" tabindex="-1" role="dialog" aria-labelledby="aurora" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="aurora">Commentaire de <%= article.title %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <% article.comments.each do |comment| %>
        <div id="comment<%= comment.id %>">

          <div class="list-group m-2">
            <p class="list-group-item"><%= tidy_date(comment.created_at) %></p>
            <p class="list-group-item">Auteur : <%= comment.user.first_name %></p>
            <p class="list-group-item"><%= comment.description  %></p>
          </div>
          <%= link_to "Supprimer le commentaire", admin_article_comment_path(comment.article, comment), method: :delete, remote: true, class: "btn btn-outline-danger m-2" %>
          <hr class="m-2">
        </div>
        <% end %>
      </div>

      <div class="modal-footer">

      </div>
      <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/articles/_like.html.erb
<% unless user_liked?(current_info) %>
<%= link_to article_like_path(current_info, find_like(current_info)[0]), method: :delete, remote: true do %>
<p class= "button-devise-like rounded mt-3 mr-4"><%= fa_icon 'thumbs-up' %>
<%= current_info.likes.length %></p>
<% end %>

<% else %>
<%= link_to article_likes_path(current_info), method: :post, remote: true do %>
  <p class= "button-devise-dislike rounded mt-3 mr-4"><%= fa_icon 'thumbs-up'%>
  <%= current_info.likes.length %></p>
  <% end %>
  <% end %>

app/views/articles/create.js.erb
$articleContainer = $('.articles');

$articleContainer.prepend("<%= j render 'admin/articles/update_article_form', article: @article %>").hide().slideDown(1500);

app/views/articles/destroy.js.erb
$deletedArticle = $('#article<%= @article.id %>');

$deletedArticle.slideUp(1500);
setTimeout(function(){
  $deletedArticle.remove()
}, 1500);

app/views/articles/index.html.erb
<%= render partial: 'shared/card_nav', locals: {info: @articles[0]} %>
<% @articles.each do |article| %>
<%= render partial: 'shared/card_picture', locals: {info: article}  %>
<% end %>
</div>

app/views/articles/update.js.erb
$previewText = $('#description<%= @article.id %>');
$previewText.fadeOut(1000).replaceWith("<%= j render 'admin/articles/preview_md', article: @article %>").fadeIn(1000)