config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  # Theme switching route !!not a page!!
  get 'theme', to: 'home#index'

  resources :supports, only: [:new, :create]
  resources :contacts, only: [:create, :index, :destroy]
  resources :landings, only: [:show]
  resources :banners do
    resources :banner_images
  end
  resources :donations, except: [:edit, :index, :show]
  resources :scores, except: [:edit]
  resources :games, except: [:edit] do
    resources :images
  end

  resources :home_tabs, only: [:create, :destroy, :update] do
    resources :ludo_images
  end

  resources :articles do
    resources :images
    resources :comments, only: [:create, :edit, :new]
    resources :likes, only: [:create, :edit, :new, :destroy]
  end
  devise_for :users, except: [:index]

  # Admin dashboard

  resources :admins, only: [:index]
  namespace :admin do
    resources :home_tabs, only: [:index]
    resources :supports, except: [:new, :create, :update, :edit]
    resources :banners
    resources :donations, only: [:edit, :index, :show]
    resources :scores, only: [:edit, :index]
    resources :games
    resources :articles do
      resources :comments
    end
    resources :users, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # TicTacToe
  namespace :tictactoe do
    resources :tictactoe_grids, only: [:update]
    resources :tictactoe_users, only: [:create, :destroy]
    resources :tictactoes, only: [:show, :create, :update] do
      get 'get_status'
      get 'get_grid'
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :likes
  has_one_attached :image
  after_create :send_news

  private

  def send_news
    users = User.all
    users.each do |user|
      UserMailer.news_actuality(self, user).deliver_now
    end
  end
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_one_attached :banner_image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user 
end
 

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :me, :class_name => "User"
  belongs_to :friend, :class_name => "User"
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :game
  belongs_to :user
  after_create :send_donation

  private

  def send_donation
    UserMailer.confirm_donation(self).deliver_now
  end
end
 

app/models/game.rb
class Game < ApplicationRecord
  has_many :donations
  has_many :scores
  has_many :users, through: :scores
  has_one_attached :image
end

app/models/home_tab.rb
class HomeTab < ApplicationRecord
	has_one_attached :ludo_image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user 
end
  

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :game
  belongs_to :user 
end
 

app/models/status.rb
class Status < ApplicationRecord
  has_many :users 
end

app/models/support.rb
class Support < ApplicationRecord
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "adresse email non valide" }
  validates :title, presence: true
  validates :description, presence: true
end

app/models/tictactoe.rb
class Tictactoe < ApplicationRecord
	has_many :tictactoe_user
	has_one :tictactoe_grid
	validates :status, presence: true

	
end

app/models/tictactoe_grid.rb
class TictactoeGrid < ApplicationRecord
	belongs_to :tictactoe
end

app/models/tictactoe_user.rb
class TictactoeUser < ApplicationRecord
	belongs_to :tictactoe
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  belongs_to :status, optional: true
  has_many :comments
  has_many :likes
  has_many :scores
  has_many :donations
  has_many :games, through: :scores
  has_one_attached :avatar
  has_many :contact, foreign_key: "friend_id", class_name: "Contact"
  after_create :set_status
  after_create :welcome_send

  private

  def set_status
    self.update(status_id: 1)
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/admin/games_controller.rb
class Admin::GamesController < AdminsController
  layout "ajax_gets"
  before_action :set_game, except: [:index, :create, :new]
  respond_to :js, :html, :json


  def index
    @games = Game.all.order('created_at DESC')
    respond_with(@articles)
  end

  def show

  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:title, :description, :link, :image)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, except: [:index, :create, :new]
  respond_to :js, :html, :json


  def index
    @games = Game.all
    respond_with(@articles)
  end

  def show

  end

  def create
    @game = Game.new(game_params)
    flash[:notice] = "Création de la partie." if @game.save
    respond_with(@game)
  end

  def update
    flash[:notice] = "Partie mise à jour." if @game.update_attributes(game_params)
    respond_with(@game)
  end

  def destroy
    flash[:notice] = "Partie supprimée" if @game.destroy
    respond_with(@game)
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.permit(:title, :description, :link, :image)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/admin/games/_new_game_form.html.erb
<div class="p-5 mb-2 bg-secondary rounded">
<%= form_tag games_path, method: :post, multipart: true, remote: true, class:"d-flex flex-column mb-3" do %>
  <%= label_tag "Titre" %>
  <%= text_field_tag :title, nil, class:"form-control mb-3" %>

  <%= label_tag "Description (markdown)" %>
  <%= text_area_tag :description, nil, class:"form-control mb-3" %>

  <%= label_tag "Lien" %>
  <%= text_field_tag :link, nil, class:"form-control mb-3"%>

  <%= label_tag "Image" %>
  <%= file_field_tag :image, class:"form-control mb-3" %>

  <%= submit_tag "Créer", class:"btn btn-info mt-2" %>
<% end %>
</div>

app/views/admin/games/_preview_md.html.erb
<div id="preview<%= game.id %>">
  <p>Prévisualisation :</p>
  <%= markdown(game.description) %>
</div>

app/views/admin/games/_update_game_form.html.erb
<div id="game<%= game.id %>" class="p-5 bg-secondary rounded mb-4">
  <h3><%= game.title %> - n°<%= game.id %></h3>
  <div class="row">

    <div class="p-2 col-8">
      <%= form_tag game_path(game), method: :patch, remote: true, class:"d-flex flex-column mb-3" do %>
      <%= label_tag "Titre" %>
      <%= text_field_tag :title, game.title, class:"form-control mb-3" %>
      <%= label_tag "Description (markdown)" %>
      <%= text_area_tag :description, game.description, class:"form-control mb-3", row: "4" %>
      <%= label_tag "Lien" %>
      <%= text_field_tag :link, game.link, class:"form-control mb-3" %>
      <div id="preview<%= game.id %>">

        <p>Prévisualisation</p>
        <%= markdown(game.description) %>

      </div>
      <%= submit_tag "Mettre à jour", class: "btn btn-info" %>
      <% end %>

      <%= link_to "Supprimer le jeu", game_path(game), method: :delete, data: { confirm: "Supprimer le jeu n°#{game.id - 1} ?"}, remote: true, class: "btn btn-danger" %>
    </div>

    <div class="p-2 col-4" id="imageContainer<%= game.id %>" style="max-width: 300px;">
      <% if game.image.attached? %>
      <%= image_tag game.image, alt: "image#{game.id}", id: "image#{game.id}" %>
      <% end %>

      <%= form_tag game_images_path(game), method: :post, multipart: true, remote: true, class:"d-flex flex-column" do %>
      <%= file_field_tag :image, class:"form-control mb-3 mt-3" %>
      <%= submit_tag "Uploader l'image", class:"btn btn-info" %>
      <% end %>

    </div>
    <hr class="m-2">
  </div>
</div>

app/views/admin/games/index.html.erb
<h2>Créer un jeu :</h2>
<%= render partial: 'new_game_form' %>

<h2>Modifier les jeux</h2>
<div id="gamesContainer">
  <% @games.each do |game| %>
  <%= render partial: 'update_game_form', locals: { game: game } %>
  <% end %>
</div>