config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  # Theme switching route !!not a page!!
  get 'theme', to: 'home#index'

  resources :supports, only: [:new, :create]
  resources :contacts, only: [:create, :index, :destroy]
  resources :landings, only: [:show]
  resources :banners do
    resources :banner_images
  end
  resources :donations, except: [:edit, :index, :show]
  resources :scores, except: [:edit]
  resources :games, except: [:edit] do
    resources :images
  end

  resources :home_tabs, only: [:create, :destroy, :update] do
    resources :ludo_images
  end

  resources :articles do
    resources :images
    resources :comments, only: [:create, :edit, :new]
    resources :likes, only: [:create, :edit, :new, :destroy]
  end
  devise_for :users, except: [:index]

  # Admin dashboard

  resources :admins, only: [:index]
  namespace :admin do
    resources :home_tabs, only: [:index]
    resources :supports, except: [:new, :create, :update, :edit]
    resources :banners
    resources :donations, only: [:edit, :index, :show]
    resources :scores, only: [:edit, :index]
    resources :games
    resources :articles do
      resources :comments
    end
    resources :users, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # TicTacToe
  namespace :tictactoe do
    resources :tictactoe_grids, only: [:update]
    resources :tictactoe_users, only: [:create, :destroy]
    resources :tictactoes, only: [:show, :create, :update] do
      get 'get_status'
      get 'get_grid'
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :likes
  has_one_attached :image
  after_create :send_news

  private

  def send_news
    users = User.all
    users.each do |user|
      UserMailer.news_actuality(self, user).deliver_now
    end
  end
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_one_attached :banner_image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user 
end
 

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :me, :class_name => "User"
  belongs_to :friend, :class_name => "User"
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :game
  belongs_to :user
  after_create :send_donation

  private

  def send_donation
    UserMailer.confirm_donation(self).deliver_now
  end
end
 

app/models/game.rb
class Game < ApplicationRecord
  has_many :donations
  has_many :scores
  has_many :users, through: :scores
  has_one_attached :image
end

app/models/home_tab.rb
class HomeTab < ApplicationRecord
	has_one_attached :ludo_image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user 
end
  

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :game
  belongs_to :user 
end
 

app/models/status.rb
class Status < ApplicationRecord
  has_many :users 
end

app/models/support.rb
class Support < ApplicationRecord
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "adresse email non valide" }
  validates :title, presence: true
  validates :description, presence: true
end

app/models/tictactoe.rb
class Tictactoe < ApplicationRecord
	has_many :tictactoe_user
	has_one :tictactoe_grid
	validates :status, presence: true

	
end

app/models/tictactoe_grid.rb
class TictactoeGrid < ApplicationRecord
	belongs_to :tictactoe
end

app/models/tictactoe_user.rb
class TictactoeUser < ApplicationRecord
	belongs_to :tictactoe
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  belongs_to :status, optional: true
  has_many :comments
  has_many :likes
  has_many :scores
  has_many :donations
  has_many :games, through: :scores
  has_one_attached :avatar
  has_many :contact, foreign_key: "friend_id", class_name: "Contact"
  after_create :set_status
  after_create :welcome_send

  private

  def set_status
    self.update(status_id: 1)
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/admins/_nav.html.erb
<nav class="nav flex-column justify-content-between bg-success align-items-center h-100" style="min-width: 150px;">
	<div class="nav-item d-flex flex-column align-items-center">
	<p class="nav-link text-light border-bottom" id="home">Espace Admin</p>
	<p class="nav-link text-light" id="users">Utilisateurs</p>
	<p class="nav-link text-light" id="articles">Articles</p>
	<p class="nav-link text-light" id="banners">Bannières</p>
	<p class="nav-link text-light" id="games">Jeux</p>
	<p class="nav-link text-light" id="scores">Scores</p>
	<p class="nav-link text-light" id="donations">Donations</p>
	<p class="nav-link text-light" id="supports">Support</p>
	<p class="nav-link text-light" id="images">Images</p>
	<%= link_to "Retour au site", root_path, class:"nav-link text-warning" %>
	</div>
	<p class="nav-link" id="year" style="display: none;"></p>
</nav>

app/views/admins/index.html.erb
<div class="d-flex h-100">
	<%= render 'nav' %>
	<div id="admin-container" class="h-100 flex-fill p-2" style="overflow: auto;">
		
	</div>
</div>

app/views/shared/_about.html.erb
<!-- /// Main Container /// -->
    <div class="container">
        <!-- /// ABOUT SECTION /// -->
        <div id="about" class="mb-5">
            <a href="about"></a><!-- Nav Anchor -->
            <div class="row heading tiny-margin">
                <div class="col-md-auto">
                    <h1 class="animation-element slide-down">A PROP<span class="colored">OS</span></h1>
                </div>
                <div class="col">
                    <hr class="animation-element extend">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <p class="small-margin">Nous sommes une équipe de développeurs passionés, qui aime le monde des jeux de sociétés. Notre seul problème était d'y jouer n'importe quand. Alors on a eu l'idée de créer Ludotopia, une plateforme qui permet de jouer à différents jeux de société en ligne !</p>
                </div>
                <div class="col-md-6">
                  <% if about != nil && about.ludo_image.attached? %>
                    <%= image_tag about.ludo_image, alt:"digital collage", class:"img-fluid b-lazy", id:"support-image" %>
                  <% end %>
                </div>
            </div>
        </div>
    </div>

app/views/shared/_card_modal.html.erb
<div class="modal fade game-modal" id="<%= current_info.id + current_info.created_at.day %>" tabindex="-1" role="dialog" aria-labelledby="aurora" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="aurora"><%= current_info.title %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <!-- <div class="modal-pic"> -->
              <% if current_info.image.attached? %>
              <%= image_tag current_info.image, alt: "#{current_info.title}", class: "modal-pic"%>
              <% end %>
        <!-- </div> -->
        <%= check_h2(markdown(current_info.description)).html_safe %>
      </div>
      <div class="modal-body">
        <!-- condition to write a comment on an article -->
        <% if current_info.class == Article %>
        <!-- add comment form -->
        <% if user_signed_in? %>
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-12" id="contactForm">
              <%= form_tag(article_comments_path(current_info), method: :post, remote: true, class: "d-flex flex-column") do %>
              <%= hidden_field_tag "user_id", current_user.id %>
              <%= text_area_tag 'description', "", placeholder: "Votre commentaire...", row: "3", class: "form-control"%>
              <%= button_tag "Envoyer", class: "button primary text-align-right" %>
              <% end %>
            </div>
          </div>
        </div>
        <% else %>
        <p><%= link_to 'Connectez-vous', new_user_session_path %> pour laisser un commentaire</p>
        <% end %>
        <!-- display to see like -->
        <% if user_signed_in? %>
        <div id="likes<%=current_info.id %>" class="mb-3">
          <%= render partial: 'articles/like', locals: {current_info: current_info} %>
        </div>
        <% else %>

        <p class="mb-3"><%= fa_icon "thumbs-up"%> <%= current_info.likes.length %></p>
        <% end %>
        <!-- display to see comments -->
        <% current_info.comments.reverse.each do |comment| %>
        <div id="comments<%= current_info.id %>">
          <%= render partial: 'articles/comment', locals: {comment: comment} %>
        </div>
        <% end %>
        <% end %>
      </div>
      <div class="modal-footer">
        <!-- condition to join a game -->
        <% if current_info.class == Game %>
        <%= link_to "Jouer", current_info.link, method: :post, class: "button primary" %>
        <% end %>
        <button type="button" class="button secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_nav.html.erb
<!-- /// GAMES SECTION /// -->
<% if info.class == Game %>
<div class="container">
  <div id="games" class="">
    <a href="games"></a><!-- Nav Anchor -->
    <div class="row heading tiny-margin">
      <div class="col-md-auto">
        <h1 class="animation-element slide-down">NOS <span class="colored">JEUX</span></h1>
      </div>
      <div class="col">
        <hr class="animation-element extend">
      </div>
    </div>
    <div class="row ">
      <div class="col-md-11 small-margin">
        <p>Nous disposons d'un panel de jeux à votre disposition pour votre bonheur. Le catalogue ne cessera de s'agrandir avec le temps.</p>
      </div>
    </div>
  </div>
</div>
<!-- /// ARTICLES SECTION /// -->
<% elsif info.class == Article %>
<div class="container">
  <div class="row heading tiny-margin">
    <div class="col-md-auto">
      <h1 class="animation-element slide-down">ARTIC<span class="colored">LES</span></h1>
    </div>
    <div class="col">
      <hr class="animation-element extend">
    </div>
  </div>
  <div class="row">
    <div class="col-md-11 small-margin">
      <p>Toute l'actualité de la plateforme de jeux, des mises à jour et des nouveautés de jeux</p>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_card_picture.html.erb
<!-- Card Index -->
<div class="container mt-5">
  <div class="row game-card pc">
    <div class="col-lg-12 col-xl-5 game-card-left">
      <div class="card-pic">
        <% if info.image.attached? %>
        <%= image_tag info.image, alt: "#{info.title}", class: "border-radius-left", data: {toggle: 'modal', target: "##{info.id + info.created_at.day}" } %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-12 col-xl-7 game-card-right border-radius-right pb-0">
      <h2 class="short-hr-left"><%= info.title %></h2>
      <p class="game-description"><%= strip_tags(markdown(info.description)[0..250]) + "..."%><span class="expand colored strong" data-toggle="modal" data-target="#<%= info.id + info.created_at.day %>">Voir plus</span></p>
      <div class="reviews d-flex align-items-baseline">
        <!-- condition to see the number of comments of the article-->
        <% if info.class == Article %>
        <div class="score-card mb-0 "id="score<%= info.id %>">
          <p class="score expand strong" data-toggle="modal" data-target="#<%= info.id + info.created_at.day %>"><%= fa_icon "thumbs-up" %> <%= info.likes.count %></p>
        </div>
        <div class="score-card" id="score-card<%=info.id %>">
          <p class="score expand strong" data-toggle="modal" data-target="#<%= info.id + info.created_at.day %>"><%= fa_icon "comment" %> <%= find_comment(info).count %></p>
        </div>
        <% elsif info.class == Game %>
        <div class="score-card mt-5">
          <p >Don<% if sum_amount(info.donations) > 1%>s<% end %> : <%= sum_amount(info.donations) %> €</p>
        </div>
        <% end %>
      </div>
    </div>
    <!-- Modal -->
    <%= render partial: 'shared/card_modal', locals: {current_info: info} %>
  </div>
</div>
<!-- Card End -->

app/views/shared/_contact.html.erb
<!-- /// CONTACT SECTION /// -->
<div class="container">
    <div id="contact" class="">
        <div class="row heading tiny-margin">
            <div class="col-md-auto">
                <h1 class="animation-element slide-down">CONT<span class="colored">ACT</span></h1>
            </div>
                <div class="col">
                    <hr class="animation-element extend">
                </div>
            </div>
            <div class="">
                <div class="row small-margin">
                    <div class="col-md-11">
                        <p>Pour tous renseignements ou questions concernant le site internet, les actualités que nous partageons ou les jeux que nous vous proposons. N’hésitez pas à nous contacter à l’aide du formulaire ci-dessous. Nous vous répondrons dans les plus brefs délais.  </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <h2 class="short-hr-left">NOUS ENVOYER UN MESSAGE</h2>
                        <div id="contactForm">
                            <%= form_tag supports_path, method: :post do %>

                            <div class="form-group">
                                <!-- Name Field -->
                            <%= text_field_tag :last_name, nil, placeholder:"Nom*"%>

                            </div>
                            <div class="form-group">
                                <!-- Email Field -->
                            <%= text_field_tag :email, nil, placeholder:"Email*"%>

                            </div>
                            <div class="form-group">
                                <!-- Title Field -->
                            <%= text_field_tag :title, nil, placeholder:"Titre*"%>

                            </div>
                            <div class="form-group">
                                <!-- Message Field -->
                                <%= text_area_tag :description, nil, placeholder:"Message*"%>
                                <p class="subtle">*Champs obligatoire</p>

                                <!-- Submit Button -->
                                <%= button_tag "ENVOYER UN MESSAGE", class:"button-devise-first", type:"submit" %>
                                <% end %>
                                <!-- Success Message -->
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h2 class="short-hr-left">AUTRES DÉTAILS</h2>
                        <div id="contact-info">
                            <ul>
                                <li><i class="fa fa-phone rounded"></i><p>Téléphone: <span class="colored">0123456789</span></p></li>
                                <li><i class="fa fa-envelope rounded"></i><p>Email: <span class="colored">thprennes7@gmail.com</span></p></li>
                                <li><i class="fa fa-map-marker rounded"></i><p>Adresse: <span class="colored">18 Rue Saint Michel, 35000 Rennes</span></p></li>
                            </ul>
                        </div>
                        <!-- Google Map -->
                        <div id="map-canvas" class="rounded"></div>
                    </div>
                </div>
        </div>
    </div><!-- Main Container End -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB64kJJiSynOc9ZqkNMOyl94cvsw5Z2uno"></script>
    <div style="visibility:hidden"><%= image_tag "map_marker.png", alt:"ybo_img" %></div>
    <%= content_for :javascript_includes do %>
        <%= javascript_include_tag 'googleMap' %>
    <% end -%>
</div>