config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  # Theme switching route !!not a page!!
  get 'theme', to: 'home#index'

  resources :supports, only: [:new, :create]
  resources :contacts, only: [:create, :index, :destroy]
  resources :landings, only: [:show]
  resources :banners do
    resources :banner_images
  end
  resources :donations, except: [:edit, :index, :show]
  resources :scores, except: [:edit]
  resources :games, except: [:edit] do
    resources :images
  end

  resources :home_tabs, only: [:create, :destroy, :update] do
    resources :ludo_images
  end

  resources :articles do
    resources :images
    resources :comments, only: [:create, :edit, :new]
    resources :likes, only: [:create, :edit, :new, :destroy]
  end
  devise_for :users, except: [:index]

  # Admin dashboard

  resources :admins, only: [:index]
  namespace :admin do
    resources :home_tabs, only: [:index]
    resources :supports, except: [:new, :create, :update, :edit]
    resources :banners
    resources :donations, only: [:edit, :index, :show]
    resources :scores, only: [:edit, :index]
    resources :games
    resources :articles do
      resources :comments
    end
    resources :users, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # TicTacToe
  namespace :tictactoe do
    resources :tictactoe_grids, only: [:update]
    resources :tictactoe_users, only: [:create, :destroy]
    resources :tictactoes, only: [:show, :create, :update] do
      get 'get_status'
      get 'get_grid'
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :likes
  has_one_attached :image
  after_create :send_news

  private

  def send_news
    users = User.all
    users.each do |user|
      UserMailer.news_actuality(self, user).deliver_now
    end
  end
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_one_attached :banner_image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user 
end
 

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :me, :class_name => "User"
  belongs_to :friend, :class_name => "User"
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :game
  belongs_to :user
  after_create :send_donation

  private

  def send_donation
    UserMailer.confirm_donation(self).deliver_now
  end
end
 

app/models/game.rb
class Game < ApplicationRecord
  has_many :donations
  has_many :scores
  has_many :users, through: :scores
  has_one_attached :image
end

app/models/home_tab.rb
class HomeTab < ApplicationRecord
	has_one_attached :ludo_image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user 
end
  

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :game
  belongs_to :user 
end
 

app/models/status.rb
class Status < ApplicationRecord
  has_many :users 
end

app/models/support.rb
class Support < ApplicationRecord
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "adresse email non valide" }
  validates :title, presence: true
  validates :description, presence: true
end

app/models/tictactoe.rb
class Tictactoe < ApplicationRecord
	has_many :tictactoe_user
	has_one :tictactoe_grid
	validates :status, presence: true

	
end

app/models/tictactoe_grid.rb
class TictactoeGrid < ApplicationRecord
	belongs_to :tictactoe
end

app/models/tictactoe_user.rb
class TictactoeUser < ApplicationRecord
	belongs_to :tictactoe
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  belongs_to :status, optional: true
  has_many :comments
  has_many :likes
  has_many :scores
  has_many :donations
  has_many :games, through: :scores
  has_one_attached :avatar
  has_many :contact, foreign_key: "friend_id", class_name: "Contact"
  after_create :set_status
  after_create :welcome_send

  private

  def set_status
    self.update(status_id: 1)
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if request.original_url.index('theme')
      if cookies[:theme].to_i == 1
        cookies.permanent[:theme] = 0
      else
        cookies.permanent[:theme] = 1
      end
      redirect_to request.referer
    end
    @banners = Banner.all.sort.reverse
    @games = Game.all.sort.reverse
    @articles = Article.all.sort.reverse
    @about = HomeTab.find_by(title: "about")
    @florian = HomeTab.find_by(title: "florian")
    @salome = HomeTab.find_by(title: "salome")
    @samir = HomeTab.find_by(title: "samir")
    @yann = HomeTab.find_by(title: "yann")
    @guillaume = HomeTab.find_by(title: "guillaume")
    @aurelien = HomeTab.find_by(title: "aurelien")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/home/_ABOUT.html.erb
<!-- /// Main Container /// -->
    <div class="container">
        <!-- /// ABOUT SECTION /// -->
        <div id="about" class="large-margin">
            <a href="about"></a><!-- Nav Anchor -->
            <div class="row heading tiny-margin">
                <div class="col-md-auto">
                    <h1 class="animation-element slide-down">ABOUT <span class="colored">US</span></h1>
                </div>
                <div class="col">
                    <hr class="animation-element extend">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <p class="small-margin">We are a dedicated team of developers, designers, artists, programmers, and most importantly gaming enthusiasts. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae ante pharetra, molestie nunc non, interdum ipsum.</p>
                    <%= image_tag "awards.png", alt:"sorry, pictures is not charge", class:" img-fluid", id:"awards" %>
                </div>
                <div class="col-md-6">
                    <%= image_tag "about.jpg", alt:"digital collage", class:"img-fluid b-lazy", id:"support-image" %>
                </div>
            </div>
        </div>
    </div>

app/views/home/_CONTACT.html.erb
<!-- /// CONTACT SECTION /// -->
        <div id="contact" class="large-margin">
            <a href="contact"></a><!-- Nav Anchor -->
            <div class="row heading tiny-margin">
                <div class="col-md-auto">
                    <h1 class="animation-element slide-down">GET IN <span class="colored">TOUCH</span></h1>
                </div>
                <div class="col">
                    <hr class="animation-element extend">
                </div>
            </div>
            <div class="">
                <div class="row small-margin">
                    <div class="col-md-11">
                        <p>We would love to hear from you. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra laoreet dolor sit amet blandit. Ut suscipit nisl ut risus volutpat malesuada.</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <h2 class="short-hr-left">LEAVE US A MESSAGE</h2>
                        <form id="contactForm" data-toggle="validator">
                            <div class="form-group">
                                <!-- Name Field -->
                                <input type="text" id="name" placeholder="Name*" required size="35" data-error="Name is required">
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <!-- Email Field -->
                                <input type="email" id="email" placeholder="Email*" required size="35" data-error="Email is required">
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <!-- Message Field -->
                                <textarea id="message" name="message" placeholder="Message*" required data-error="Message cannot be empty"></textarea>
                                <p class="subtle">* required field</p>
                                <div class="help-block with-errors"></div>
                                <!-- Submit Button -->
                                <button type="submit" class="button">SEND MESSAGE</button>
                                <!-- Success Message -->
                                <div id="msgSubmit" class="text-center hidden"></div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6">
                        <h2 class="short-hr-left">OUR DETAILS</h2>
                        <div id="contact-info">
                            <ul>
                                <li><i class="fa fa-phone"></i><p>Phone: <span class="colored"><a href="tel:+1(803)635585">+1 (803) 635 585</a></span></p></li>
                                <li><i class="fa fa-envelope"></i><p>Email: <span class="colored"><a href="mailto:office@example.com">office@example.com</a></span></p></li>
                                <li><i class="fa fa-globe"></i><p>Website: <span class="colored"><a href="www.atypicalthemes.com" target="_blank">www.atypicalthemes.com</a></span></p></li>
                                <li><i class="fa fa-map-marker"></i><p>Address: <span class="colored">1168 12th Street East Oconomowoc, WI 53066</span></p></li>
                            </ul>
                        </div>
                        <!-- Google Map -->
                    </div>
                </div>
            </div>
        </div>
    </div><!-- Main Container End -->

app/views/home/_HIRING.html.erb
        <!-- /// CAREERS SECTION /// -->
        <div id="careers" class='large-margin'>
            <a href="careers"></a><!-- Nav Anchor -->
            <div class="row heading tiny-margin">
                <div class="col-md-auto">
                    <h1 class="animation-element slide-down">WE'RE <span class="colored">HIRING</span></h1>
                </div>
                <div class="col">
                    <hr class="animation-element extend">
                </div>
            </div>
            <div class="row medium-margin">
                <div class="col-md-11">
                    <h2 class="short-hr-left">JOB OPENINGS</h2>
                    <p>Are you a talented and motivated individual? Then we would love to have you in our team. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, nisl non mattis sollicitudin, risus quam tempor sem, vel interdum est libero non odio.</p><br>
                </div>
                <div class="col-md-4">
                    <div class="job-card">
                        <h3 class="colored">LEAD PROGRAMMER</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        <button class="button" data-toggle="modal" data-target="#modal1">View Details</button>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="lead-programmer" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h2 class="modal-title colored" id="lead-programmer">LEAD PROGRAMMER</h2>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <h3>THE IDEAL CANDIDATE:</h3>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, nisl non mattis sollicitudin, risus quam tempor sem, vel interdum est libero non odio.</p>
                                    <br>
                                    <h3>REQUIREMENTS:</h3>
                                    <ul>
                                    <li><p>B.Sc. in Computer Science and/or Mathematics</p></li>
                                    <li><p>Proficient with c++ and object-oriented programming</p></li>
                                    <li><p>Development experience in the games industry a plus.</p></li>
                                    <li><p>Ability to contribute innovative and original ideas towards all aspects of game production and development</p></li>
                                    <li><p>Strong communication and organizational skills</p></li>
                                    <li><p>Must work well under pressure and handle multiple tasks</p></li>
                                    <li><p>Passion for making GREAT games</p></li>
                                    </ul>
                                    <br>
                                    <h3>HOW TO APPLY:</h3>
                                    <p>If you think you have what it takes to join our team you an apply here <a href="mailto:office@example.com" >office@example.com</a></p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="button secondary" data-dismiss="modal">Close</button>
                                    <a href="mailto:office@example.com" class="button">Apply</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="job-card">
                        <h3 class="colored">LEVEL DESIGNER</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        <button class="button" data-toggle="modal" data-target="#modal2">View Details</button>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade " id="modal2" tabindex="-1" role="dialog" aria-labelledby="level-designer" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h2 class="modal-title colored" id="level-designer">LEVEL DESIGNER</h2>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <h3>THE IDEAL CANDIDATE:</h3>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, nisl non mattis sollicitudin, risus quam tempor sem, vel interdum est libero non odio.</p>
                                    <br>
                                    <h3>REQUIREMENTS:</h3>
                                    <ul>
                                    <li><p>B.Sc. in Computer Science and/or Mathematics</p></li>
                                    <li><p>Proficient with c++ and object-oriented programming</p></li>
                                    <li><p>Development experience in the games industry a plus.</p></li>
                                    <li><p>Ability to contribute innovative and original ideas towards all aspects of game production and development</p></li>
                                    <li><p>Strong communication and organizational skills</p></li>
                                    <li><p>Must work well under pressure and handle multiple tasks</p></li>
                                    <li><p>Passion for making GREAT games</p></li>
                                    </ul>
                                    <br>
                                    <h3>HOW TO APPLY:</h3>
                                    <p>If you think you have what it takes to join our team you an apply here <a href="mailto:office@example.com" >office@example.com</a></p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="button secondary" data-dismiss="modal">Close</button>
                                    <a href="mailto:office@example.com" class="button">Apply</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="job-card">
                        <h3 class="colored">AI ENGINEER</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        <button class="button" data-toggle="modal" data-target="#modal3">View Details</button>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade " id="modal3" tabindex="-1" role="dialog" aria-labelledby="ai-engineer" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h2 class="modal-title colored" id="ai-engineer">AI ENGINEER</h2>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                               <div class="modal-body">
                                    <h3>THE IDEAL CANDIDATE:</h3>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, nisl non mattis sollicitudin, risus quam tempor sem, vel interdum est libero non odio.</p>
                                    <br>
                                    <h3>REQUIREMENTS:</h3>
                                    <ul>
                                    <li><p>B.Sc. in Computer Science and/or Mathematics</p></li>
                                    <li><p>Proficient with c++ and object-oriented programming</p></li>
                                    <li><p>Development experience in the games industry a plus.</p></li>
                                    <li><p>Ability to contribute innovative and original ideas towards all aspects of game production and development</p></li>
                                    <li><p>Strong communication and organizational skills</p></li>
                                    <li><p>Must work well under pressure and handle multiple tasks</p></li>
                                    <li><p>Passion for making GREAT games</p></li>
                                    </ul>
                                    <br>
                                    <h3>HOW TO APPLY:</h3>
                                    <p>If you think you have what it takes to join our team you an apply here <a href="mailto:office@example.com" >office@example.com</a></p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="button secondary" data-dismiss="modal">Close</button>
                                    <a href="mailto:office@example.com" class="button">Apply</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2 class="short-hr-center">OUR NEWSLETTER</h2>
                    <p>Stay up to date with the team and our products by subscribing to our newsletter.</p>
                    <form id="newsletter" data-toggle="validator">
                        <input type="email" id="emailsign" placeholder="Your email adress"> <!-- Email Field -->
                        <button type="submit" id="form-signup" class="button">SUBSCRIBE</button>
                        <div id="msgSignup" class="h3 text-center hidden"></div>
                    </form>
                </div>
            </div>
        </div>

app/views/home/_TEAM.html.erb
           
        <!-- /// TEAM SECTION /// -->
        <div id="team" class="large-margin">
            <a href="team"></a><!-- Nav Anchor -->
            <div class="row heading tiny-margin">
                <div class="col-md-auto">
                    <h1 class="animation-element slide-down">THE <span class="colored">TEAM</span></h1>
                </div>
                <div class="col">
                    <hr class="animation-element extend">
                </div>
            </div>
            <div class="row medium-margin">
                <div class="col-md-11 tiny-margin">
                    <p>Our passion unites us. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt mi ut mauris varius, vitae lobortis erat ullamcorper. Pellentesque vel dolor non nisi fringilla scelerisque in non ante.</p>
                </div>
                <div id="full-row" class="row text-center">
                    <div class="col-md-3 team-card">
                        <figure>
                            <img src="images/placeholder.jpg" data-src="images/team.jpg" class="img-fluid b-lazy" alt="teammember">
                            <figcaption class="team-caption">
                                <p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit.”</p>
                                <hr class="hr-short">
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook fa-lg"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter fa-lg"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin fa-lg"></i></a></li>
                                </ul>
                            </figcaption>
                        </figure>
                        <p class="team-name">Vladimir M.</p>
                        <p class="subtle">Lead Designer</p>
                    </div>
                    <div class="col-md-3 team-card">
                        <figure>
                            <img src="images/placeholder.jpg" data-src="images/team.jpg" class="img-fluid b-lazy" alt="teammember">
                            <figcaption class="team-caption">
                                <p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit.”</p>
                                <hr class="hr-short">
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook fa-lg"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter fa-lg"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin fa-lg"></i></a></li>
                                </ul>
                            </figcaption>
                        </figure>
                        <p class="team-name">Asimov R.</p>
                        <p class="subtle">Founder</p>
                    </div>
                    <div class="col-md-3 team-card">
                        <figure>
                            <img src="images/placeholder.jpg" data-src="images/team.jpg" class="img-fluid b-lazy" alt="teammember">
                            <figcaption class="team-caption">
                                <p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit.”</p>
                                <hr class="hr-short">
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook fa-lg"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter fa-lg"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin fa-lg"></i></a></li>
                                </ul>
                            </figcaption>
                        </figure>
                        <p class="team-name">Natalia I.</p>
                        <p class="subtle">Lead Artist</p>
                    </div>
                    <div class="col-md-3 team-card">
                        <figure>
                            <img src="images/placeholder.jpg" data-src="images/team.jpg" class="img-fluid b-lazy" alt="teammember">
                            <figcaption class="team-caption">
                                <p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit.”</p>
                                <hr class="hr-short">
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook fa-lg"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter fa-lg"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin fa-lg"></i></a></li>
                                </ul>
                            </figcaption>
                        </figure>
                        <p class="team-name">Dimitri A.</p>
                        <p class="subtle">Programmer</p>
                    </div>
                </div>
            </div>
            <div class="row tiny-margin">
                <div class="col-md-11">
                    <h2 class="short-hr-left">OUR STUDIO</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, nisl non mattis sollicitudin, risus quam tempor sem, vel interdum est libero non odio.</p>
                </div>
            </div>
            <div class="grid-gallery">
                <div class="row">
                    <div class="col-md-4 gallery-item">
                        <a href="images/studio.jpg" data-lightbox="studio_gallery">
                            <div class="overlay gallery">
                                <i class="fa fa-picture-o fa-3x"></i>
                            </div>
                            <img src="images/placeholder.jpg" data-src="images/studio.jpg" class="img-fluid b-lazy" alt="">
                        </a>
                    </div>
                    <div class="col-md-4 gallery-item">
                        <a href="images/studio.jpg" data-lightbox="studio_gallery">
                            <div class="overlay gallery">
                                <i class="fa fa-picture-o fa-3x"></i>
                            </div>
                            <img src="images/placeholder.jpg" data-src="images/studio.jpg" class="img-fluid b-lazy" alt="">
                        </a>
                    </div>
                    <div class="col-md-4 gallery-item">
                        <a href="images/studio.jpg" data-lightbox="studio_gallery">
                            <div class="overlay gallery">
                                <i class="fa fa-picture-o fa-3x"></i>
                            </div>
                            <img src="images/placeholder.jpg" data-src="images/studio.jpg" class="img-fluid b-lazy" alt="">
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 gallery-item">
                        <a href="images/studio.jpg" data-lightbox="studio_gallery">
                            <div class="overlay gallery">
                                <i class="fa fa-picture-o fa-3x"></i>
                            </div>
                            <img src="images/placeholder.jpg" data-src="images/studio.jpg" class="img-fluid b-lazy" alt="">
                        </a>
                    </div>
                    <div class="col-md-4 gallery-item">
                        <a href="images/studio.jpg" data-lightbox="studio_gallery">
                            <div class="overlay gallery">
                                <i class="fa fa-picture-o fa-3x"></i>
                            </div>
                            <img src="images/placeholder.jpg" data-src="images/studio.jpg" class="img-fluid b-lazy" alt="">
                        </a>
                    </div>
                    <div class="col-md-4 gallery-item">
                        <a href="images/studio.jpg" data-lightbox="studio_gallery">
                            <div class="overlay gallery">
                                <i class="fa fa-picture-o fa-3x"></i>
                            </div>
                            <img src="images/placeholder.jpg" data-src="images/studio.jpg" class="img-fluid b-lazy" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>

app/views/home/index.html.erb
<!--ybo: test render for integration -->
<%= render 'particule' %>
<div class="container">
	<!-- view 3 last articles -->
	<%= render partial: 'shared/card_nav', locals: {info: @articles[0]} %>
	<% x = 0 %>
	<% 3.times do %>
	<% unless @articles[x] == nil %>
	<%= render partial: 'shared/card_picture', locals: {info: @articles[x]} %>
	<% end -%>
	<% x += 1 %>
	<% end %>
	<%= link_to "Plus d'articles", articles_path, class: "d-flex justify-content-end p-3 mb-3" %>

	<!-- view 3 last games -->
	<%= render partial: 'shared/card_nav', locals: {info: @games[0]} %>
	<% x = 0 %>
	<% 3.times do %>
	<% unless @games[x] == nil %>
	<%= render partial: 'shared/card_picture', locals: {info: @games[x]}  %>
	<% end -%>
	<% x += 1 %>
	<% end %>
	<%= link_to "Plus de jeux", games_path, class: "d-flex justify-content-end p-3 mb-3" %>
</div>
<%= render partial: 'shared/about', locals: { about: @about } %>
<%= render partial: 'team', locals: { florian: @florian, aurelien: @aurelien, yann: @yann, salome: @salome, samir: @samir, guillaume: @guillaume } %>